apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ADOScaffoldermeta
  title: Azure DevOps Pipeline
  description: A template for invoking an Azure DevOps pipeline
spec:
  owner: your-company
  type: azure-devops-pipeline
  parameters:
    - name: sourcePath
      description: The path to the source code
      type: string
    - name: environment
      description: The target deployment environment
      type: string

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
